version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always

  web:
    ports:
      - 80:80
    image: ghcr.io/bitbyt3r/magpetsvs-web:main
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  game:
    image: ghcr.io/bitbyt3r/magpetsvs-game:main
    depends_on:
      - redis
      - crossbar
    env_file:
      - .env
    restart: always

  crossbar:
    ports:
      - 8080:8080
    image: ghcr.io/bitbyt3r/magpetsvs-crossbar:main
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always