version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  web:
    build: web
    ports:
      - 80:80
    image: ghcr.io/bitbyt3r/magpetsvs-web:latest
    depends_on:
      - redis
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      AWS_S3_BUCKET: "magpets"
      AWS_REGION: "us-east-1:${AWS_REGION}"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      START_SCORE: 1500

  game:
    build: game
    ports:
      - 8081:8081
    image: ghcr.io/bitbyt3r/magpetsvs-game:latest
    depends_on:
      - redis
      - crossbar
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      AUTOBAHN_ROUTER: "ws://crossbar:8080/ws"

  crossbar:
    build: crossbar
    ports:
      - 8080:8080
    image: ghcr.io/bitbyt3r/magpetsvs-crossbar:latest