---
name: Build Crossbar Image

on:
  push:
    paths:
      - crossbar/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and Push Crossbar Image
        uses: docker/build-push-action@v2
        with:
          context: "crossbar"
          push: true
          tags: ghcr.io/bitbyt3r/magpetsvs-crossbar:${{ github.ref_name }}
