---
name: Build Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Game Image
        uses: docker/build-push-action@v2
        with:
          context: "game"
          push: true
          tags: ghcr.io/${{ github.repository }}-game:${{ github.ref_name }}
      
      - name: Build and Push Web Image
        uses: docker/build-push-action@v2
        with:
          context: "web"
          push: true
          tags: ghcr.io/${{ github.repository }}-web:${{ github.ref_name }}
      
      - name: Build and Push Crossbar Image
        uses: docker/build-push-action@v2
        with:
          context: "crossbar"
          push: true
          tags: ghcr.io/${{ github.repository }}-crossbar:${{ github.ref_name }}
